# Generated by Django 5.2.13 on 2026-04-23 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='phishing_detection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=30000)),
                ('Prediction', models.CharField(max_length=300)),
            ],
            options={
                'permissions': [('can_predict', 'Can predict URL'), ('can_view_all_predictions', 'Can view all predictions'), ('can_train_model', 'Can train ML model')],
            },
        ),
    ]
