# Generated by Django 5.2.13 on 2026-04-25 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('can_train_model', 'Can train ML model'), ('can_view_dashboard', 'Can view dashboard'), ('can_view_users', 'Can view users'), ('can_view_predictions', 'Can view predictions'), ('can_view_analytics', 'Can view analytics')],
            },
        ),
        migrations.DeleteModel(
            name='phishing_detection',
        ),
    ]
